services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker  # <- CAMBIADO
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


